# Generated by Django 3.1.4 on 2024-02-18 06:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_extension', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('customer_cc_email', models.TextField(null=True)),
                ('customer_bcc_email', models.TextField(null=True)),
                ('customer_type', models.CharField(choices=[('INTERNATIONAL', 'INTERNATIONAL'), ('MASS', 'MASS'), ('AMAZON SELLER', 'AMAZON SELLER'), ('RETAIL', 'RETAIL'), ('CLOSE OUTS', 'CLOSE OUTS'), ('HOME EMPLOYEE', 'HOME EMPLOYEE')], max_length=50)),
                ('customer_company', models.CharField(max_length=100)),
                ('customer_category', multiselectfield.db.fields.MultiSelectField(choices=[('LUXURY', 'LUXURY'), ('MAKEUP', 'MAKEUP'), ('FMCG', 'FMCG'), ('HAIRCARE', 'HAIRCARE'), ('SKINCARE', 'SKINCARE')], max_length=36)),
                ('customer_rank', models.CharField(choices=[('DIAMOND', 'DIAMOND'), ('PLATINUM', 'PLATINUM'), ('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE'), ('IN HOME', 'INHOME')], max_length=50)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('staff_id', models.CharField(max_length=50)),
            ],
        ),
    ]
