# Generated by Django 3.1.4 on 2024-01-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INTERNATIONAL', 'INTERNATIONAL'), ('MASS', 'MASS'), ('AMAZON SELLER', 'AMAZON SELLER'), ('RETAIL', 'RETAIL'), ('CLOSE OUTS', 'CLOSE OUTS'), ('HOME EMPLOYEE', 'HOME EMPLOYEE')], max_length=50),
        ),
    ]
