# Generated by Django 3.1.4 on 2024-01-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20240127_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('upc', models.CharField(max_length=200)),
                ('item_classification', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=600)),
                ('on_hand', models.IntegerField()),
                ('allocated', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
