# Generated by Django 3.1.4 on 2024-01-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20240127_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOutReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('item_description', models.CharField(max_length=700)),
                ('qty_in', models.PositiveIntegerField(default=0)),
                ('qty_out', models.PositiveIntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
