# Generated by Django 3.1.4 on 2024-01-28 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inoutreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowMoversReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('upc', models.CharField(max_length=200)),
                ('item_classification', models.CharField(choices=[('BAGS', 'BAGS'), ('BAKING SODA', 'BAKING SODA'), ('BELT', 'BELT'), ('BELTS', 'BELTS'), ('CANDLES', 'CANDLES'), ('DENTALCARE', 'DENTAL CARE'), ('DEODORANT', 'DEODORANT'), ('EAU PERFUMES', 'EAU PERFUMES'), ('EDC PERFUMES', 'EDC PERFUMES'), ('EDP PERFUMES', 'EDP PERFUMES'), ('EDT PERFUMES', 'EDT PERFUMES'), ('FRAGRANCE LOTION', 'FRAGRANCE LOTION'), ('FRAGRANCE MIST', 'FRAGRANCE MIST'), ('GLASSES', 'GLASSES'), ('GROOMING', 'GROOMING'), ('HAIR BRUSH', 'HAIR BRUSH'), ('HAIR STRAIGHTENER', 'HAIR STRAIGHTENER'), ('HAIRCARE', 'HAIRCARE'), ('HEALTHCARE', 'HEALTHCARE'), ('HOMECARE', 'HOMECARE'), ('JEWELRY', 'JEWELRY'), ('MAKEUP', 'MAKEUP'), ('MEDICATION', 'MEDICATION'), ('NAIL POLISH', 'NAIL POLISH'), ('PERFUMES', 'PERFUMES'), ('PERFUMES SET', 'PERFUMES SET'), ('PERSONAL CARE', 'PERSONAL CARE'), ('SAMPLE', 'SAMPLE'), ('SHOES', 'SHOES'), ('SKINCARE', 'SKINCARE'), ('TESTER', 'TESTER'), ('WATCH', 'WATCH'), ('WATER BOTTLES', 'WATER BOTTLES')], max_length=200)),
                ('description', models.CharField(max_length=700)),
                ('qtyin_oneyear', models.IntegerField()),
                ('qtyout_oneyear', models.IntegerField()),
                ('balance_oneyear', models.IntegerField()),
                ('available', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('begining_balance', models.IntegerField()),
                ('reference', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sellercategory', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Slow Mover Report',
                'verbose_name_plural': 'Slow Movers Reports',
                'unique_together': {('report_date', 'sku')},
            },
        ),
    ]
