# Generated by Django 3.1.4 on 2024-01-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_slowmoversreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='slowmoversreport',
            name='brand',
            field=models.CharField(default='-', max_length=300),
            preserve_default=False,
        ),
    ]
