# Generated by Django 3.1.4 on 2024-02-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('brand_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='brands/')),
            ],
        ),
    ]
