# Generated by Django 3.1.4 on 2024-02-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_conatctus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConatctUs',
            new_name='ContactUs',
        ),
    ]
