# Generated by Django 3.1.4 on 2024-02-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240225_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_testmonial', models.TextField()),
                ('slide_img', models.ImageField(upload_to='add_slides')),
            ],
        ),
    ]
