# Generated by Django 3.1.4 on 2024-02-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='slide_label',
            field=models.CharField(default='12:00', max_length=200),
            preserve_default=False,
        ),
    ]
