# Generated by Django 3.1.4 on 2024-01-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default='3pl transaction number'),
            preserve_default=False,
        ),
    ]
