# Generated by Django 3.1.4 on 2024-01-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20240119_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(default='3pl transaction number', max_length=100),
        ),
    ]
