# Generated by Django 3.1.4 on 2024-02-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('name', models.CharField(default='Gmail Configuration', max_length=100)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('username', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('staff_id', models.CharField(editable=False, max_length=50, unique=True)),
            ],
        ),
    ]
