# Generated by Django 3.1.4 on 2024-01-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('upc', models.BigIntegerField()),
                ('description', models.CharField(max_length=600)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Haircare', 'Haircare'), ('Skincare', 'Skincare'), ('Makeup', 'Makeup'), ('FMCG', 'FMCG'), ('Accessories', 'Accessories')], max_length=200)),
                ('available_qty', models.IntegerField()),
                ('msrp', models.FloatField()),
                ('discount', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('required_qunatity', models.IntegerField()),
            ],
        ),
    ]
