# Generated by Django 3.1.4 on 2024-01-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20240116_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weekly_Offers',
            new_name='Weekly_Offer',
        ),
    ]
