# Generated by Django 3.1.4 on 2024-02-04 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0005_brandoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandoffer',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandoffer',
            name='created_person_email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandoffer',
            name='created_person_first_name',
            field=models.CharField(default='DefaultFirstName', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandoffer',
            name='created_person_last_name',
            field=models.CharField(default='DefaultLastName', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandoffer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now().date()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandoffer',
            name='offer_file',
            field=models.FileField(default='default_offer.pdf', upload_to='offers/brandoffer/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandoffer',
            name='offer_type',
            field=models.CharField(choices=[('SALON', 'SALON'), ('REGULAR', 'REGULAR')], default='REGULAR', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandoffer',
            name='reason_for_offer_generation',
            field=models.TextField(default='Initial reason'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandoffer',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now().time()),
            preserve_default=False,
        ),
    ]
