# Generated by Django 3.1.4 on 2024-02-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20240204_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='created_person_email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='brandoffer',
            name='created_person_first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brandoffer',
            name='created_person_last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brandoffer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brandoffer',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
