# Generated by Django 3.1.4 on 2024-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20240204_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='created_person_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='brandoffer',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='brandoffer',
            name='time',
            field=models.TimeField(),
        ),
    ]
