# Generated by Django 3.1.4 on 2024-02-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20240204_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='offer_file',
            field=models.FileField(upload_to=''),
        ),
    ]
