# Generated by Django 3.1.4 on 2024-02-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20240204_1934'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='brandoffer',
            name='offer_file',
            field=models.FileField(upload_to='offers/brandoffer/'),
        ),
    ]
